name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        echo "venv created"
        pwd
        ls -al
        ls -al venv
        . venv/bin/activate
        pip install -r requirements.txt
      shell: bash

    - name: Run tests
      run: |
        . venv/bin/activate
        python -m unittest discover -s tests
      shell: bash

    - name: List files for debugging
      run: ls -R
      shell: bash